def dna(s):
    n = [0, 0, 0, 0]
    for nucleotide in s: # +1 to each index of n according to the type of nucleotide
        if nucleotide == "A":
            n[0] += 1
        elif nucleotide == "C":
            n[1] += 1
        elif nucleotide == "G":
            n[2] += 1
        elif nucleotide == "T":
            n[3] += 1
    return " ".join([str(x) for x in n]) # format output

print(dna("GACGCTCAATTTGCATTAATTAGGCACCGAGTATCGCGATGGCGAGCGGCTAGAGGTACAACGTGATCACAGTGGTCTGATTTACTATCTGGACTGCAATCCTGCACCTCGACAGATGTGTCGATCCAGCTGTGCGCACCGAACGCAACGGGCAACTGTTGAGCATCCCATGGTCCTCCTTGCGCTCTGCCTAACCCCCGGATATGAACACATGATTTCCATACGAAGTCGTCGATAGGTCTGAGATCCATCTCTCTCAGAACACTGATACCGGAATCGCGATTACCAGTGTATGTCGGGTCCTCGAGACTCGACTTGTGAACCCGGTTCTTTACGGGCAGTAAACCCCCCCCCGAGGTCTGAGGGCCCAGGCTGATATGTGTGCTCACGCATGGGTTCCCTAAAATGAGCGAGCTTCCGAGGTCCTGCGGACCAACCGTAGAACTCCACGTTCAGTTCACTGATAGTCTGGAGGATGTTTTTTTACTTACGTGGGGCGCCCGGCAGAATTTCTCTCGCATATTTGATGCATACCCGGGTGTCGCTGTGGGACCGCCCTTAATTTTAGCAAATTTTTGACCGAGACGGTCGGGGTAGGATTACGTGTCGAGACTTCCGACTTGGTTTAAGATCTGGGCAGGTGCACGATTCCAGCATCGAAAGGGGCCGCCTCAAGCAGTGCCTCGACAATCAGTATGAAATTTCATTGACCCTAACACAAGTGATGATCCGCCTCAGGTGACGTGAAGATGATTCTGATTGGTATGTGGGTCTGACCTCATTGTTCGCGGTTCGCTCAGCTGGTGCCGGATGCCGTATATCCCGTATTAATGCGGCCGGGATTCCTGCACTCTGATGTTCGCAGTGGTCGTATACTCATCCG"))