def subs(s, t):
    locations = []
    for i in range(len(s) - len(t)): # subtract len(t) so that way the index doesn't go out of range
        if s[i:i + len(t)] == t:
            locations += [i + 1]
    locations_string = " ".join(map(str, locations)) # format output
    return locations_string

print(subs("CGTTATGTTCGTTATGCGCGTTATGCGTTATGCGTTATGGTCGTTATGCCAGCTAGTAGCTCCGTTATGCGTTATGCGTTATGCGTTATGGTTTTTGTGTCGTTATGTGGCGTTATGCGTTATGTCGTTATGTTCGTTATGGACGTTATGGGCACGTTATGTACGCGTTATGCGTTATGGCGTTATGCACAACGTTATGCGTTATGACGTTATGTGGCGTTATGACGTTATGGCGTTATGGCGTTATGCGTGGGGAGCCGTTATGTCGTTACCAGTGGCGTTATGTCGTTATGCGTTATGCCGTTATGGATGGCTCGTTATGCTCGTTATGCGTTATGACCTCGTTATGTGACGTTATGCGTTATGATCGTTATGGCGTTATGCAAGTCAGACAGGCGTCGTTATGGGTAACCGTTATGGCGTTATGCAGCGTTATGCGTTATGACGTTATGGACGTTATGCGTTATGCGGGTCCGTTATGGAGCGTTATGCGTTATGATCGAGATACGTTATGCCCGTTATGAGCGTTATGGCGTTATGCGTTATGAGCGTTATGTTTTGCGTTATGGGGCGTTATGATCGTTATGGCGTTATGCCGTTATGTGACGTTATGTCGTTATGCACCGTTATGGTCGTTATGGTCCGTTATGCGTTATGTCGTTATGTATTTCGTTATGATATGCGTTATGCGTTATGCGTTATGGGTTCGTTATGACCGTTATGAGCAGGGCTCGTTATGGACGTTATGCGTTATGAAGTAACGGATCACGTTATGCTCCGTTATGCTCGTTATGGGGGTCGTTATGGCGTTATGCGTTATGGGGCGCGTTATGCGTTATGGCGTTATGTTCGTTATGACGTTATGTGCGTTATGACGTTATGCGTTATGTGAGGGCGTTATGTCGTTATGACGACCGTTATGGCGTTATGTCGTTATGACGTTATGGTACGTTATG", "CGTTATGCG"))