def subs(s, t):
    locations = []
    for i in range(len(s) - len(t)):
        print("test")
        if s[i:i + len(t)] == t:
            print("test test")
            locations += [i + 1]
    locations_string = " ".join(map(str, locations))
    return locations_string

print(subs("CGTTATGTTCGTTATGCGCGTTATGCGTTATGCGTTATGGTCGTTATGCCAGCTAGTAGCTCCGTTATGCGTTATGCGTTATGCGTTATGGTTTTTGTGTCGTTATGTGGCGTTATGCGTTATGTCGTTATGTTCGTTATGGACGTTATGGGCACGTTATGTACGCGTTATGCGTTATGGCGTTATGCACAACGTTATGCGTTATGACGTTATGTGGCGTTATGACGTTATGGCGTTATGGCGTTATGCGTGGGGAGCCGTTATGTCGTTACCAGTGGCGTTATGTCGTTATGCGTTATGCCGTTATGGATGGCTCGTTATGCTCGTTATGCGTTATGACCTCGTTATGTGACGTTATGCGTTATGATCGTTATGGCGTTATGCAAGTCAGACAGGCGTCGTTATGGGTAACCGTTATGGCGTTATGCAGCGTTATGCGTTATGACGTTATGGACGTTATGCGTTATGCGGGTCCGTTATGGAGCGTTATGCGTTATGATCGAGATACGTTATGCCCGTTATGAGCGTTATGGCGTTATGCGTTATGAGCGTTATGTTTTGCGTTATGGGGCGTTATGATCGTTATGGCGTTATGCCGTTATGTGACGTTATGTCGTTATGCACCGTTATGGTCGTTATGGTCCGTTATGCGTTATGTCGTTATGTATTTCGTTATGATATGCGTTATGCGTTATGCGTTATGGGTTCGTTATGACCGTTATGAGCAGGGCTCGTTATGGACGTTATGCGTTATGAAGTAACGGATCACGTTATGCTCCGTTATGCTCGTTATGGGGGTCGTTATGGCGTTATGCGTTATGGGGCGCGTTATGCGTTATGGCGTTATGTTCGTTATGACGTTATGTGCGTTATGACGTTATGCGTTATGTGAGGGCGTTATGTCGTTATGACGACCGTTATGGCGTTATGTCGTTATGACGTTATGGTACGTTATG", "CGTTATGCG"))